menu:
  "Blog": /
  "Conférences": /talks
  Projets Web": /projects

links:
  "Photos": /photos/
  "@oncletom": https://twitter.com/oncletom
  "GitHub": https://github.com/oncletom
  "RSS Feed": /feed/

less:
  paths:
    - bower_components/bootstrap/less
