menu:
  Blog: /
  Conférences: /talks
  Projets Web: /projects

links:
  RSS: /feed/
  Twitter: https://twitter.com/oncletom
  Code: https://github.com/oncletom
  Photos: http://flickr.com/photos/the-jedi/