menu:
  Home: /
  Archives: /archives

widgets: 
- search
- category

excerpt_link: Read More

addthis:
  enable: false

twitter:
  username:
  show_replies: false
  tweet_count: 5

fancybox: true

rss:
